MOKO-1438 add moko mvvm + add view model + add sample
icerockdev/moko-compose-multiplatform-template pull request #2
Opened 2023-03-16 07:15 UTC by BorisTrubitsyn

Add moko mvvm library added and a simple usage example given

2023-03-20 08:34 UTC, Alex009 requested changes

2023-03-20 08:34 UTC, Alex009 commented on shared/src/desktopMain/kotlin/main.desktop.kt
> +@Composable fun MainView() = App(viewModel)
what is it? revert please

2023-03-20 08:34 UTC, Alex009 commented on shared/src/desktopMain/kotlin/main.desktop.kt
> +    App(viewModel)
what is it? revert please

2023-03-20 08:34 UTC, Alex009 commented on shared/src/iosMain/kotlin/main.ios.kt
> +fun MainViewController() = ComposeUIViewController { App(viewModel) }
what is it? revert please

2023-03-20 08:34 UTC, Alex009 commented on shared/src/commonMain/kotlin/App.kt
> +        var isShowMokoMvvmView by remember { mutableStateOf(false) }
i think we should create enum here that will be simplified navigation:
```
enum Screen {
    HelloWorld,
    SimpleViewModel
}

var currentScreen: Screen by remember { motableStateOf(Screen.HelloWorld) }

when(currentScreen) {
    HelloWorld -> HelloWorldScreen()
    SimpleViewModel -> SimpleViewModelScreen()
}
```

2023-03-20 10:46 UTC, BorisTrubitsyn commented on shared/src/desktopMain/kotlin/main.desktop.kt
> +@Composable fun MainView() = App(viewModel)
my fault, deleted

2023-03-20 10:46 UTC, BorisTrubitsyn commented on shared/src/desktopMain/kotlin/main.desktop.kt
> +    App(viewModel)
done

2023-03-20 10:47 UTC, DenielGrin commented on shared/src/iosMain/kotlin/main.ios.kt
> +fun MainViewController() = ComposeUIViewController { App(viewModel) }
done

2023-03-20 11:02 UTC, DenielGrin commented on shared/src/commonMain/kotlin/App.kt
> +        var isShowMokoMvvmView by remember { mutableStateOf(false) }
Agree. Routes changed using enum class

2023-03-27 05:49 UTC, Alex009 commented
@BorisTrubitsyn merge actual `main` to this branch and fix conflicts please

2023-03-27 12:25 UTC, BorisTrubitsyn commented
@Alex009 Actual main is merged

2023-04-08 13:49 UTC, Alex009 requested changes

2023-04-08 13:49 UTC, Alex009 commented on settings.gradle.kts
> +        mavenLocal()
remove this before merge

2023-04-08 16:52 UTC, Alex009 approved these changes

2023-04-08 16:53 UTC, merged